// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually, unless you know your concept requires a custom instantiation procedure.

import { SyncConcept } from "@engine";

export const Engine = new SyncConcept();

import { getDb } from "@utils/database.ts";

import ScheduleGeneratorConcept from "./ScheduleGenerator/ScheduleGeneratorConcept.ts";
import FriendListConcept from "./FriendList/FriendListConcept.ts";
import RequestingConcept from "./Requesting/RequestingConcept.ts";
import SessioningConcept from "./Sessioning/SessioningConcept.ts";
import UserAuthenticationConcept from "./UserAuthentication/UserAuthenticationConcept.ts";
import MessagingConcept from "./Messaging/MessagingConcept.ts";

export type { default as ScheduleGeneratorConcept } from "./ScheduleGenerator/ScheduleGeneratorConcept.ts";
export type { default as FriendListConcept } from "./FriendList/FriendListConcept.ts";
export type { default as RequestingConcept } from "./Requesting/RequestingConcept.ts";
export type { default as SessioningConcept } from "./Sessioning/SessioningConcept.ts";
export type { default as UserAuthenticationConcept } from "./UserAuthentication/UserAuthenticationConcept.ts";
export type { default as MessagingConcept } from "./Messaging/MessagingConcept.ts";

// Initialize the database connection
export const [db, client] = await getDb();

export const ScheduleGenerator = Engine.instrumentConcept(new ScheduleGeneratorConcept(db));
export const FriendList = Engine.instrumentConcept(new FriendListConcept(db));
export const Requesting = Engine.instrumentConcept(new RequestingConcept(db));
export const Sessioning = Engine.instrumentConcept(new SessioningConcept(db));
export const UserAuthentication = Engine.instrumentConcept(new UserAuthenticationConcept(db));
export const Messaging = Engine.instrumentConcept(new MessagingConcept(db));
