// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually.


import type { Sync } from "@engine";

import * as sync_UserAuthentication from "./UserAuthentication.sync.ts";
import * as sync_ScheduleGenerator from "./ScheduleGenerator.sync.ts";
import * as sync_sample from "./sample.sync.ts";

const allSyncs: Record<string, Sync> = {};


for (const [name, func] of Object.entries(sync_UserAuthentication)) {
  if (typeof func === "function") {
    allSyncs[`UserAuthentication.${name}`] = func as Sync;
  }
}
for (const [name, func] of Object.entries(sync_ScheduleGenerator)) {
  if (typeof func === "function") {
    allSyncs[`ScheduleGenerator.${name}`] = func as Sync;
  }
}
for (const [name, func] of Object.entries(sync_sample)) {
  if (typeof func === "function") {
    allSyncs[`sample.${name}`] = func as Sync;
  }
}

export default allSyncs;
