// This file is auto-generated by the `generate_imports.ts` script.
// Do not edit it manually.


import type { Sync } from "@engine";



const allSyncs: Record<string, Sync> = {};



export default allSyncs;
